name: fltext
description: "Text editor built using Flutter."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0-120.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^6.1.1
  flutter_spinkit: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.1
  system_theme: ^2.3.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  flex_color_picker: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  menu_bar: ^0.5.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png