name: Build / Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: beta # Puts some pressure on us to support future versions easily
          cache: true
      - run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      
